#!/usr/bin/env bash
# Debugging to find out what is keeping my Ubuntu container's...
# Nginx installation from listening on port 80
# Delete the existing ../sites-enabled/default and replace it with a copy of
# ../sites-available/default. Do that by creating a symbolic link
# The flag -s creates a symbolic link, -f deletes the existing file and replaces it
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default
/etc/nginx/sites-enabled/default
service nginx restart
