#!/usr/bin/env bash
# Debugging nginx (service (init) must say that nginx is not running)
# configures a server to listening on port 80 of all servers active IPv4 IPs
ln -sf /etc/nginx/sites-available/default
/etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)”
