#!/usr/bin/env bash
# Debugging nginx (service (init) must say that nginx is not running)
# configures a server to listening on port 80 of all servers active IPv4 IPs
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
